# Generated by Django 4.1.5 on 2023-01-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='experience',
        ),
        migrations.AddField(
            model_name='person',
            name='name_terms',
            field=models.CharField(choices=[('Basic', (('mr', 'Mr'), ('ms', 'Ms'))), ('Prof', (('dr', 'Dr'), ('sir', 'Sir'))), ('unknown', 'Unknown')], default=(('dr', 'Dr'), ('sir', 'Sir')), max_length=255, verbose_name=''),
        ),
    ]
