# Generated by Django 4.1.5 on 2023-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_child_experience_person_name_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Не повторяющися id человека'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Не повторяющися id человека'),
        ),
    ]
